### ISSUE TITLE
Passing dictionary does not succeed

### ISSUE THREAD

**Issue by szwijsen** [boriel/perlfunc#1]
Hi,

I'm trying to use this to call a perl function with a python dictionary as arguments.
But I can't get it to work: looks like it assigns the element key name to the value as well, instead of the actual value.
I played around with args/kwargs in calling the function, but that didn't solve it.

Can you give an example of how to call a function with a dictionary? Probably I'm calling it wrong.

In my case, I have a GenCallMonLog.pl with perl function named pythonLog.
I can call that from a test perl script like this (simplified to essential since not all code is public):
```
#!/usr/bin/perl
require "./GenCallMonLog.pl";
my %testhash;
%testhash = ('Message' => 'Starting TEST Monitor', 'EventID' => 'TST-2000');
pythonLog(%testhash);
```
This works fine (it writes entries to a log file).
So I try to do the same from a python script using perlfunc:
```
#!/usr/bin/env python
import os
import sys
from perlfunc import perl5lib, perlfunc, perlreq
logparams = {'Message':'Starting TEST Monitor', 'EventID':'TST-2000'}
@perlfunc
@perl5lib('.')
@perlreq('GenCallMonLog.pl')
def pythonLog(logdict):
  pass # empty body needed
pythonLog(logparams)
```
This is the result:
```
Traceback (most recent call last):
  File "./NetMon.py", line 21, in <module>
    pythonLog(logparams)
  File "perlfunc.py", line 173, in new
    result_stdout = sys_exec([PERL] + [tmpname], False, env=env)
  File "perlfunc.py", line 51, in sys_exec
    raise BaseException(str(a.communicate()[1]))
BaseException: EventID (EventID): Invalid value.
```
In Debug mode of perlfunc I see that the .pl in /tmp has this:
`@rst = (pythonLog((EventID => 'EventID', Message => 'Message')));`
So, the values are the same as the keys.

As said, probably I'm passing the args wrong? So an example from your end could be sufficient ;-)

**Comment by boriel** [comment]
This is long unmaintained (13+ years) and untested. I fixed the bug you comment.
Can you try now?

**Comment by szwijsen** [comment]
Ah, I saw more recent commit dates, so I thought it was still active.
This fixes the issue indeed (should have seen that myself though :-) ).
Although old code, it still comes in handy for me now, thanks!

**Comment by boriel** [comment]
Glad to hear that!! :-)
